{{- if .Values.openshift -}}
{{- if (semverCompare ">=1.9-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
apiVersion: route.openshift.io/v1
{{- else }}
apiVersion: v1
{{- end }}
{{- if .Values.controller.apisvc.route.enabled }}
kind: Route
metadata:
  name: neuvector-route-api
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  to:
    kind: Service
    name: neuvector-svc-controller-api
  port:
    targetPort: controller-api
  tls:
    termination: {{ .Values.controller.apisvc.route.termination }}
{{ end -}}
{{- if .Values.controller.federation.mastersvc.type }}
---
{{- if (semverCompare ">=1.9-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
apiVersion: route.openshift.io/v1
{{- else }}
apiVersion: v1
{{- end }}
kind: Route
metadata:
  name: neuvector-route-fed-master
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  to:
    kind: Service
    name: neuvector-svc-controller-fed-master
  port:
    targetPort: fed
  tls:
    termination: {{ .Values.controller.federation.mastersvc.route.termination }}
{{ end -}}
{{- if .Values.controller.federation.managedsvc.type }}
---
{{- if (semverCompare ">=1.9-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
apiVersion: route.openshift.io/v1
{{- else }}
apiVersion: v1
{{- end }}
kind: Route
metadata:
  name: neuvector-route-fed-managed
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  to:
    kind: Service
    name: neuvector-svc-controller-fed-managed
  port:
    targetPort: fed
  tls:
    termination: {{ .Values.controller.federation.managedsvc.route.termination }}
{{ end -}}
{{- end -}}
