# Default values for neuvector.
# This is a YAML-formatted file.
# Declare variables to be passed into the templates.

registry: docker.io
tag: latest
imagePullSecrets: {}

controller:
  # If false, controller will not be installed
  enabled: true
  image:
    repository: neuvector/controller
  replicas: 3

enforcer:
  # If false, enforcer will not be installed
  enabled: true
  image:
    repository: neuvector/enforcer

manager:
  # If false, manager will not be installed
  enabled: true
  image:
    repository: neuvector/manager
  env:
    ssl: on
  svc:
    type: NodePort

cve:
  updater:
    # If false, cve updater will not be installed
    enabled: true
    image:
      repository: neuvector/updater
      tag: latest
    schedule: "0 0 * * *"
