{{- if and .Values.manager.enabled .Values.manager.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: neuvector-webui-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
  - host: {{ .Values.manager.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: neuvector-service-webui
          servicePort: 8443
{{- end }}